# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'photos/'
collections:
  - name: 'posts'
    label: 'Billets de blog'
    folder: '_posts/'
    create: true
    slug: '/blog/{{categories}}/{{year}}/{{month}}/{{day}}/{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Item', name: 'active-item', widget: 'hidden', default: 'blog' }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Auteur', name: 'auteur', widget: 'string' }
      - { label: 'Catégorie', name: 'category', widget: 'list', options: ['Avant-guerre', 'Famille', 'Guerre', 'Peinture', 'Divers'] }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
