# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'photos/wordpress/'
publish_mode: editorial_workflow
collections:
  - name: 'posts'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Item', name: 'active-item', widget: 'hidden', default: 'blog' }
      - { label: 'Photo d’en-tête', name: 'picture', widget: 'image' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Auteur', name: 'auteur', widget: 'string' }
      - { label: 'Catégorie', name: 'category', widget: 'select', options: ['Avant-guerre', 'Famille', 'Guerre', 'Peinture', 'Divers'] }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'expositions'
    label: 'Expositions / Exhibitions'
    folder: '_expositions/'
    create: true
    slug: 'exposition-{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre (non affiché)', name: 'title', widget: 'string' }
      - { label: 'En cours ?', name: 'en-cours', widget: 'boolean' }
      - { label: 'Date (fr)', name: 'date-fr', widget: 'string' }
      - { label: 'Description (fr)', name: 'description-fr', widget: 'markdown' }
      - { label: 'Date (en)', name: 'date-en', widget: 'string' }
      - { label: 'Description (en)', name: 'description-en', widget: 'markdown' }
      - { label: 'Date (ru)', name: 'date-ru', widget: 'string' }
      - { label: 'Description (ru)', name: 'description-ru', widget: 'markdown' }
  - name: 'retrospective'
    label: 'Rétrospective'
    folder: '_retrospective/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre (fr)', name: 'title-fr', widget: 'string' }
      - { label: 'Titre (en)', name: 'title-en', widget: 'string' }
      - { label: 'Titre (ru)', name: 'title-ru', widget: 'string' }
      - { label: 'Photo', name: 'picture', widget: 'image' }
      - { label: 'Lieu / Place', name: 'place', widget: 'string' }
      - { label: 'Dimensions', name: 'dimensions', widget: 'string' }
      - { label: 'Description (fr)', name: 'description-fr', widget: 'markdown' }
      - { label: 'Description (en)', name: 'description-en', widget: 'markdown' }
      - { label: 'Description (ru)', name: 'description-ru', widget: 'markdown' }
  - name: 'biography-fr'
    label: 'Biographie (fr)'
    folder: 'biographie/'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'paintings-fr'
    label: 'Peinture (fr)'
    folder: 'peintures/'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'biography-en'
    label: 'Biography (en)'
    folder: 'en/biography/'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'paintings-en'
    label: 'Paintings (en)'
    folder: 'en/paintings/'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'biography-ru'
    label: 'Biography (ru)'
    folder: 'ru/biography/'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'paintings-ru'
    label: 'Paintings (ru)'
    folder: 'ru/paintings/'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
