# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'photos/'
collections:
  - name: 'posts'
    label: 'Billets de blog'
    folder: '_posts/'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Item', name: 'active-item', widget: 'hidden', default: 'blog' }
      - { label: 'Titre', name: 'title', widget: 'text'}
      - { label: 'Catégorie', name: 'category', widget: 'list', options: ['Avant-guerre', 'Famille', 'Guerre', 'Peinture', 'Divers'] }
