# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'photos/wordpress/'
collections:
  - name: 'posts'
    label: 'Posts'
    folder: '_posts/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Item', name: 'active-item', widget: 'hidden', default: 'blog' }
      - { label: 'Photo d’en-tête', name: 'picture', widget: 'image' }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Auteur', name: 'auteur', widget: 'string' }
      - { label: 'Catégorie', name: 'category', widget: 'select', options: ['Avant-guerre', 'Famille', 'Guerre', 'Peinture', 'Divers'] }
      - { label: 'Body', name: 'body', widget: 'markdown' }
