name: Trigger Netlify Build
on:
  schedule:
    # Run at 0815 daily
    - cron: '0 4 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/618014c418edaa61e3f0db87
